CREATE TABLE solicitudes_inscripcion (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    torneo_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    telefono_contacto VARCHAR(40) NULL,
    creado_en DATETIME NOT NULL,
    jugador1_id BIGINT NULL,
    jugador1_nombre VARCHAR(80) NULL,
    jugador1_apellido VARCHAR(80) NULL,
    jugador1_genero VARCHAR(20) NULL,
    jugador1_telefono VARCHAR(40) NULL,
    jugador1_fecha_nacimiento DATE NULL,
    jugador2_id BIGINT NULL,
    jugador2_nombre VARCHAR(80) NULL,
    jugador2_apellido VARCHAR(80) NULL,
    jugador2_genero VARCHAR(20) NULL,
    jugador2_telefono VARCHAR(40) NULL,
    jugador2_fecha_nacimiento DATE NULL,
    CONSTRAINT fk_solicitud_torneo FOREIGN KEY (torneo_id) REFERENCES torneos(id),
    CONSTRAINT fk_solicitud_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id),
    CONSTRAINT fk_solicitud_jugador1 FOREIGN KEY (jugador1_id) REFERENCES jugadores(id),
    CONSTRAINT fk_solicitud_jugador2 FOREIGN KEY (jugador2_id) REFERENCES jugadores(id)
);
