ALTER TABLE lugares ADD COLUMN archivado TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE categorias ADD COLUMN archivado TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE temporadas ADD COLUMN archivado TINYINT(1) NOT NULL DEFAULT 0;
